# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'Super8oard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NMapsMap'
  # Pods for Super8oard

end
